# ops/config.yaml
# Central configuration file for pypyr pipelines
# Customize these values as needed

registry: docker.io
image_name: imprvai/imprv_pgvectorscale
pg_version: '17'
vectorscale_ref: '0.9.0'
multiarch: true
push: false

